" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

call plug#begin('~/dotfiles/vim/plugged')
Plug 'altercation/vim-colors-solarized'
Plug 'cespare/vim-toml'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'dart-lang/dart-vim-plugin'
Plug 'dense-analysis/ale'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'guns/vim-sexp'
Plug 'hanschen/vim-ipython-cell', { 'for': 'python' }
Plug 'hanschen/vim-ipython-cell', { 'for': 'python' }
Plug 'hashivim/vim-terraform'
Plug 'itchyny/lightline.vim'
Plug 'jnurmine/Zenburn'
Plug 'jpalardy/vim-slime', { 'for': 'python' } " Needed for vim-ipython-cell
Plug 'jpalardy/vim-slime', { 'for': 'python' } " Needed for vim-ipython-cell
Plug 'sevko/vim-nand2tetris-syntax'
Plug 'terryma/vim-expand-region'
Plug 'thosakwe/vim-flutter'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fireplace'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-sexp-mappings-for-regular-people'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-scripts/indentpython.vim'
call plug#end()

let mapleader = ","
let maplocalleader = "-"

" Because it almost was.
nnoremap <C-c> <Esc>
inoremap <C-c> <Esc>
vnoremap <C-c> <Esc>

" Move between splits easier
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Horizontal to Right Vertical Split
nnoremap <leader>v <C-w>H <C-w>r

" Switch syntax highlighting on
syntax on

" ColorSchema
let g:dracula_italic = 0
colorscheme dracula
set background=dark
highlight Normal ctermbg=None
if (has("termguicolors"))
  set termguicolors
endif
set colorcolumn=88

set backspace=indent,eol,start " Make backspace behave in a sane manner

" Highlight search results
set hlsearch

" Show matches as search is typed
set incsearch

" Setting for whitespace visualization
set list
set listchars=trail:·,tab:\ \

" Always ensure there is a status bar
set laststatus=2

" Leader b to redraw because I override <C-l> for window changing
nnoremap <leader>b :redraw!<cr>
" Leader n to remove highlighted search fields
nnoremap <leader>n :nohlsearch<cr>
" Leader s to save all files
nnoremap <leader>s :wa<cr>
" Leader r to resize
nnoremap <leader>r :resize<space>
" Set up Ctrl-P Fuzzy File Finder
let g:ctrlp_map = '<leader>t'
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
let g:ctrlp_custom_ignore = '\v[\/](target|out|nashorn_code_cache|node_modules|coverage)$'

" Set the status line
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P

" Show line, column, %, at bottom of window
set ruler

" Don't wrap long lines
set nowrap

" Searches are case-sensitive only if they contain upper-case
set ignorecase
set smartcase

" Begin scrolling before hitting edges
set scrolloff=0

" Store temporary files in one place
set backupdir=~/.vim-tmp
set directory=~/.vim-tmp

" tab->spaces and such
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent
autocmd FileType python set shiftwidth=4 tabstop=4 softtabstop=4 expandtab
autocmd FileType yaml set shiftwidth=2 tabstop=2 softtabstop=2 expandtab

" vsplit opens to the right instead of left
set splitright
" split opens below instead of pushing current down
set splitbelow

" When doing :e <tab> shows list of possible completions like in bash.
set wildmode=list:longest,full

" Remove trailing whitespace on save and keep cursor position.
function! <SID>StripTrailingWhitespaces()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfun
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

" :Ggrep symbol under cursor
function! GgrepCursor()
  let expr="'\\<" . expand("<cword>") . "\\>'"
  call fugitive#GrepCommand(3, -1, 0, 0, "", expr)
  copen
endfunction

map <BS> :call GgrepCursor()<cr>

" Trigger `autoread` when files changes on disk
" https://unix.stackexchange.com/questions/149209/refresh-changed-content-of-file-opened-in-vim/383044#383044
" https://vi.stackexchange.com/questions/13692/prevent-focusgained-autocmd-running-in-command-line-editing-mode
" Need vim-tmux-focus-events plugin and `set -g focus-events on` in .tmux.conf
autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * if mode() != 'c' | checktime | endif

" Filetypes
autocmd BufNewFile,BufRead *.boot set filetype=clojure
autocmd BufNewFile,BufRead *.mat set filetype=matlab
autocmd BufNewFile,BufRead *.avsc set filetype=json

" Compile latex
autocmd BufWritePost, *.tex silent! execute "!/Library/TeX/texbin/pdflatex <afile>" | redraw!

" lightline
set noshowmode " remove redundant -- Insert -- below lightline
let g:lightline = {
      \ 'colorscheme': 'dracula',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
      \   'right': [ [ 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'fileformat', 'fileencoding', 'filetype' ] ],
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head',
      \   'fileformat': 'LightlineFileformat',
      \   'filetype': 'LightlineFiletype',
      \   'fileencoding': 'LightlineFileencoding',
      \   'percent': 'LightlinePercent',
      \ },
      \ }

function! LightlineFileformat()
  return winwidth(0) > 93 ? &fileformat : ''
endfunction

function! LightlineFiletype()
  return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
endfunction

function! LightlineFileencoding()
  return winwidth(0) > 93 ? &fileencoding : ''
endfunction

function! LightlinePercent()
  return winwidth(0) > 70 ? (100 * line('.') / line('$')) . '%' : ''
endfunction

" Linters
let g:ale_linters = {'clojure': ['clj-kondo'], 'openscad': ['SCA2D']}
let g:ale_set_highlights = 0
let g:ale_sign_column_always = 0

let g:slime_target = "tmux"
let g:slime_no_mappings = 1
let g:slime_python_ipython = 1
xnoremap cpp <Plug>SlimeRegionSend
nnoremap cpp <Plug>SlimeParagraphSend
nnoremap cpv <Plug>SlimeConfig

" Clojure
autocmd FileType clojure nnoremap <buffer> cpe :%Eval<cr>
autocmd FileType clojure nnoremap <buffer> <localleader>c :CljEval (let [builds (into [] (shadow.cljs.devtools.api/active-builds))] (case (count builds) 0 (throw (ex-info "no active builds!" {})) 1 (shadow.cljs.devtools.api/repl (first builds)) (do (println "Pick one of the following:") (doseq [[i build-id] (map-indexed vector builds)] (println i build-id)) (println) (let [choice (Integer. (read-line))] (shadow.cljs.devtools.api/repl (get builds choice))))))<cr>
autocmd FileType clojure nnoremap <buffer> <localleader>C :CljsEval :repl/quit<cr>
autocmd FileType clojure inoremap #?<space>( #?(
" Docs for the below are at https://github.com/clojure-vim/clojure.vim
let g:clojure_fuzzy_indent_patterns = ['^with', '^def', '^let', '^fdef', '^render']
" The '^:' stops it from indenting reader conditionals like #?(:clj ...) as
" when you then have :cljs on the next line you don't want it indented.
let g:clojure_fuzzy_indent_blacklist = ['^:']
let g:clojure_align_multiline_strings = 1
let g:clojure_discard_macro = 1
let g:clojure_maxlines = 1000

" Git
nnoremap <leader>ga :Git add -p <cr>
nnoremap <leader>gc :Git commit <cr>
nnoremap <leader>gp :Git push <cr>
nnoremap <leader>gs :Git status <cr>

" Flutter
let g:flutter_split_height = 10
let g:flutter_autoscroll = 1

" Helps ctrl-p with large trees, specifically E363: pattern uses more memory than 'maxmempattern'
set mmp=5000
