if [[ $(uname) == 'Darwin' ]]; then
        source /usr/local/opt/git/etc/bash_completion.d/git-completion.bash
        source /usr/local/opt/git/etc/bash_completion.d/git-prompt.sh
        export PATH=/usr/local/bin:$PATH
        export PATH=$PATH:/Library/TeX/texbin
        for f in /usr/local/etc/bash_completion.d/*; do source $f; done
        alias aa="export PATH=~/miniconda3/bin:$PATH"
        alias deep="osascript ~/dotfiles/applescript/deep.scpt"
        alias shallow="osascript ~/dotfiles/applescript/shallow.scpt"
fi

if [[ $(uname) == 'Linux' ]]; then
        source /etc/bash_completion.d/git-prompt
        alias ls='ls --color=auto'
        alias aa="export PATH=/opt/anaconda3/bin:$PATH"
fi

# Avoid duplicates
export HISTCONTROL=ignoreboth:erasedups
export HISTFILESIZE=-1
export HISTSIZE=-1
export HISTTIMEFORMAT="[%h %d %H:%M:%S] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend

source ~/dotfiles/bash/bash_colors
export GIT_PS1_SHOWDIRTYSTATE="true"
export GIT_PS1_SHOWSTASHSTATE="true"
export GIT_PS1_SHOWUNTRACKEDFILES="true"
export GIT_PS1_SHOWUPSTREAM="auto"

if [ "$SSH_CONNECTION" ] || [ "$SSH_CLIENT" ] || [ "$SSH_TTY" ]; then
        PS1='\u@\h:\W/ $(__git_ps1 "\[$txtcyn\](%s)")\[$txtrst\]\$ '
else
        PS1='\W/ $(__git_ps1 "\[$txtcyn\](%s)")\[$txtrst\]\$ '
fi

bind 'set completion-ignore-case on'
export EDITOR=vim
export CLICOLOR=1
export LSCOLORS=exfxbxdxcxegedabagacad

alias o="open"
#alias pi="ssh pi@192.168.1.13"

alias gf='fg'
alias asa='source activate' # anaconda source activate
alias asd='source deactivate' # anaconda source deactivate
